import mongoose from "mongoose";

const formSchema = new mongoose.Schema({
    isCompleted: Boolean,
    date_init: String,
    weight_init: String,
    color_cassava: String,
    state_cassava: String,
    texture_cassava: String,
    external_help: String,
    date_end: String,
    weight_end: String,
    starch_end: String,
    how_fermented: String,
    minTemp_day_0: Number,
    medTemp_day_0: Number,
    maxTemp_day_0: Number,
    precipitation_day_0: Number,
    minHum_day_0: Number,
    maxHum_day_0: Number,
    minTemp_day_1: Number,
    medTemp_day_1: Number,
    maxTemp_day_1: Number,
    precipitation_day_1: Number,
    minHum_day_1: Number,
    maxHum_day_1: Number,
    minTemp_day_2: Number,
    medTemp_day_2: Number,
    maxTemp_day_2: Number,
    precipitation_day_2: Number,
    minHum_day_2: Number,
    maxHum_day_2: Number,
    minTemp_day_3: Number,
    medTemp_day_3: Number,
    maxTemp_day_3: Number,
    precipitation_day_3: Number,
    minHum_day_3: Number,
    maxHum_day_3: Number,
    minTemp_day_4: Number,
    medTemp_day_4: Number,
    maxTemp_day_4: Number,
    precipitation_day_4: Number,
    minHum_day_4: Number,
    maxHum_day_4: Number,
    minTemp_day_5: Number,
    medTemp_day_5: Number,
    maxTemp_day_5: Number,
    precipitation_day_5: Number,
    minHum_day_5: Number,
    maxHum_day_5: Number,
    minTemp_day_6: Number,
    medTemp_day_6: Number,
    maxTemp_day_6: Number,
    precipitation_day_6: Number,
    minHum_day_6: Number,
    maxHum_day_6: Number,
    minTemp_day_7: Number,
    medTemp_day_7: Number,
    maxTemp_day_7: Number,
    precipitation_day_7: Number,
    minHum_day_7: Number,
    maxHum_day_7: Number,
    minTemp_day_8: Number,
    medTemp_day_8: Number,
    maxTemp_day_8: Number,
    precipitation_day_8: Number,
    minHum_day_8: Number,
    maxHum_day_8: Number,
    minTemp_day_9: Number,
    medTemp_day_9: Number,
    maxTemp_day_9: Number,
    precipitation_day_9: Number,
    minHum_day_9: Number,
    maxHum_day_9: Number
});

const Form = mongoose.model("Form", formSchema);

export default Form;
