import mongoose from "mongoose";

const formSchema = new mongoose.Schema({
    isCompleted: Boolean,
    date_init: String,
    weight_init: String,
    color_cassava: String,
    state_cassava: String,
    texture_cassava: String,
    external_help: String,
    date_end: String,
    weight_end: String,
    starch_end: String,
    how_fermented: String,
    minTemp_aqui_0: Number,
    medTemp_aqui_0: Number,
    maxTemp_aqui_0: Number,
    precipitation_aqui_0: Number,
    minHum_aqui_0: Number,
    maxHum_aqui_0: Number,
    minTemp_aqui_1: Number,
    medTemp_aqui_1: Number,
    maxTemp_aqui_1: Number,
    precipitation_aqui_1: Number,
    minHum_aqui_1: Number,
    maxHum_aqui_1: Number,
    minTemp_aqui_2: Number,
    medTemp_aqui_2: Number,
    maxTemp_aqui_2: Number,
    precipitation_aqui_2: Number,
    minHum_aqui_2: Number,
    maxHum_aqui_2: Number,
    minTemp_aqui_3: Number,
    medTemp_aqui_3: Number,
    maxTemp_aqui_3: Number,
    precipitation_aqui_3: Number,
    minHum_aqui_3: Number,
    maxHum_aqui_3: Number,
    minTemp_aqui_4: Number,
    medTemp_aqui_4: Number,
    maxTemp_aqui_4: Number,
    precipitation_aqui_4: Number,
    minHum_aqui_4: Number,
    maxHum_aqui_4: Number,
    minTemp_aqui_5: Number,
    medTemp_aqui_5: Number,
    maxTemp_aqui_5: Number,
    precipitation_aqui_5: Number,
    minHum_aqui_5: Number,
    maxHum_aqui_5: Number,
    minTemp_aqui_6: Number,
    medTemp_aqui_6: Number,
    maxTemp_aqui_6: Number,
    precipitation_aqui_6: Number,
    minHum_aqui_6: Number,
    maxHum_aqui_6: Number,
    minTemp_aqui_7: Number,
    medTemp_aqui_7: Number,
    maxTemp_aqui_7: Number,
    precipitation_aqui_7: Number,
    minHum_aqui_7: Number,
    maxHum_aqui_7: Number,
    minTemp_aqui_8: Number,
    medTemp_aqui_8: Number,
    maxTemp_aqui_8: Number,
    precipitation_aqui_8: Number,
    minHum_aqui_8: Number,
    maxHum_aqui_8: Number,
    minTemp_aqui_9: Number,
    medTemp_aqui_9: Number,
    maxTemp_aqui_9: Number,
    precipitation_aqui_9: Number,
    minHum_aqui_9: Number,
    maxHum_aqui_9: Number
});

const Form = mongoose.model("Form", formSchema);

export default Form;
